on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - "!*"

name: CI

env:
  CI: 1
  TRAVIS_BUILD_DIR: ${{ github.workspace }}

jobs:
  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Set running flag
        run: echo "::set-env name=RUNNING::1"
      - uses: actions/checkout@v2
      - uses: technote-space/get-git-comment-action@v1
      - uses: technote-space/get-diff-action@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PREFIX_FILTER: |
            resources/
          SUFFIX_FILTER: |
            .js
            .ts
            .vue
          FILES: .eslintrc
        if: "! contains(env.COMMIT_MESSAGE, '[skip ci]') && ! contains(env.COMMIT_MESSAGE, '[ci skip]')"
      - name: Set running flag
        run: echo "::set-env name=RUNNING::"
        if: "! env.GIT_DIFF"

      - name: Get Yarn Cache Directory
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
        if: env.RUNNING
      - name: Cache node dependencies
        uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
        if: env.RUNNING
      - name: Install Package dependencies
        run: yarn install
        if: env.RUNNING
      - name: Check code style
        run: yarn eslint ${{ env.GIT_DIFF }}
        if: env.RUNNING
      - uses: 8398a7/action-slack@v2
        with:
          status: failure
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: failure()

  stylelint:
    name: stylelint
    runs-on: ubuntu-latest
    steps:
      - name: Set running flag
        run: echo "::set-env name=RUNNING::1"
      - uses: actions/checkout@v2
      - uses: technote-space/get-git-comment-action@v1
      - uses: technote-space/get-diff-action@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PREFIX_FILTER: |
            resources/
          SUFFIX_FILTER: |
            .scss
            .css
          FILES: .stylelintrc.json
        if: "! contains(env.COMMIT_MESSAGE, '[skip ci]') && ! contains(env.COMMIT_MESSAGE, '[ci skip]')"
      - name: Set running flag
        run: echo "::set-env name=RUNNING::"
        if: "! env.GIT_DIFF"

      - name: Get Yarn Cache Directory
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
        if: env.RUNNING
      - name: Cache node dependencies
        uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
        if: env.RUNNING
      - name: Install Package dependencies
        run: yarn install
        if: env.RUNNING
      - name: Check code style
        run: yarn stylelint ${{ env.GIT_DIFF }}
        if: env.RUNNING
      - uses: 8398a7/action-slack@v2
        with:
          status: failure
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: failure()

  phpcs:
    name: PHP Code Sniffer
    runs-on: ubuntu-latest
    steps:
      - name: Set running flag
        run: echo "::set-env name=RUNNING::1"
      - uses: actions/checkout@v2
      - uses: technote-space/get-git-comment-action@v1
      - uses: technote-space/get-diff-action@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SUFFIX_FILTER: .php
          FILES: phpcs.xml
        if: "! contains(env.COMMIT_MESSAGE, '[skip ci]') && ! contains(env.COMMIT_MESSAGE, '[ci skip]')"
      - name: Set running flag
        run: echo "::set-env name=RUNNING::"
        if: "! env.GIT_DIFF"

      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"
        if: env.RUNNING
      - name: Cache composer modules
        uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-
        if: env.RUNNING
      - name: Install Composer dependencies
        run: composer install
        if: env.RUNNING
      - name: Check code style
        run: vendor/bin/phpcs --standard=./phpcs.xml ${{ env.GIT_DIFF }}
        if: env.RUNNING
      - uses: 8398a7/action-slack@v2
        with:
          status: failure
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: failure()

  phpmd:
    name: PHPMD
    runs-on: ubuntu-latest
    steps:
      - name: Set running flag
        run: echo "::set-env name=RUNNING::1"
      - uses: actions/checkout@v2
      - uses: technote-space/get-git-comment-action@v1
      - uses: technote-space/get-diff-action@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SUFFIX_FILTER: .php
          SEPARATOR: ','
          FILES: phpmd.xml
        if: "! contains(env.COMMIT_MESSAGE, '[skip ci]') && ! contains(env.COMMIT_MESSAGE, '[ci skip]')"
      - name: Set running flag
        run: echo "::set-env name=RUNNING::"
        if: "! env.GIT_DIFF"

      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"
        if: env.RUNNING
      - name: Cache composer modules
        uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-
        if: env.RUNNING
      - name: Install Composer dependencies
        run: composer install
        if: env.RUNNING
      - name: Check code style
        run: vendor/bin/phpmd ${{ env.GIT_DIFF }} ansi phpmd.xml
        if: env.RUNNING
      - uses: 8398a7/action-slack@v2
        with:
          status: failure
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: failure()

  cover:
    name: Coverage
    needs: eslint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['11', '12']
    steps:
      - name: Set running flag
        run: echo "::set-env name=RUNNING::1"
      - uses: actions/checkout@v2
      - uses: technote-space/get-git-comment-action@v1
      - uses: technote-space/get-diff-action@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PREFIX_FILTER: |
            resources/
          SUFFIX_FILTER: |
            .js
            .ts
            .vue
          FILES: |
            yarn.lock
            jest.config.js
        if: "! contains(env.COMMIT_MESSAGE, '[skip ci]') && ! contains(env.COMMIT_MESSAGE, '[ci skip]')"
      - name: Set running flag
        run: echo "::set-env name=RUNNING::"
        if: "! env.GIT_DIFF"
      - name: Set running flag
        if: matrix.node == '12' && startsWith(github.ref, 'refs/tags/')
        run: echo "::set-env name=RUNNING::1"
      - name: Set running flag
        run: |
          if [[ ! -f package.json ]] || ! < package.json jq -r '.scripts | keys[]' | grep -qe '^cover$'; then
            echo "::set-env name=RUNNING::"
          fi

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
        if: env.RUNNING
      - name: Get Yarn Cache Directory
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
        if: env.RUNNING
      - name: Cache node dependencies
        uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
        if: env.RUNNING
      - name: Install Package dependencies
        run: yarn install
        if: env.RUNNING
      - name: Run tests
        run: yarn cover
        if: env.RUNNING
      - name: Codecov
        run: |
          if [ -n "$CODECOV_TOKEN" ]; then
            curl -s https://codecov.io/bash | bash -s -- -t $CODECOV_TOKEN -f $COVERAGE_FILE
          fi
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
          COVERAGE_FILE: ./coverage/js/lcov.info
        if: env.RUNNING && matrix.node == '12'
      - uses: 8398a7/action-slack@v2
        with:
          status: failure
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: failure()

  phpunit:
    name: PHPUnit
    needs: [phpcs, phpmd]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['7.2', '7.3']
    steps:
      - name: Set running flag
        run: echo "::set-env name=RUNNING::1"
      - uses: actions/checkout@v2
      - uses: technote-space/get-git-comment-action@v1
      - uses: technote-space/get-diff-action@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SUFFIX_FILTER: .php
          FILES: composer.lock
        if: "! contains(env.COMMIT_MESSAGE, '[skip ci]') && ! contains(env.COMMIT_MESSAGE, '[ci skip]')"
      - name: Set running flag
        run: echo "::set-env name=RUNNING::"
        if: "! env.GIT_DIFF"
      - name: Set running flag
        if: matrix.SEND_CODECOV == 1 && startsWith(github.ref, 'refs/tags/')
        run: echo "::set-env name=RUNNING::1"
      - name: Set running flag
        run: |
          if [[ ! -f composer.json ]] || ! < composer.json jq -r '.scripts | keys[]' | grep -qe '^phpunit$'; then
            echo "::set-env name=RUNNING::"
          fi

      - name: Switch PHP version
        env:
          PHP_VERSION: ${{ matrix.php }}
        run: sudo ln -sf "/usr/bin/php$PHP_VERSION" /etc/alternatives/php
        if: env.RUNNING
      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"
        if: env.RUNNING
      - name: Cache composer modules
        uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-
        if: env.RUNNING
      - name: Install Composer dependencies
        run: composer install
        if: env.RUNNING
      - name: Run tests
        run: composer phpunit
        if: env.RUNNING
      - name: Codecov
        run: |
          if [ -n "$CODECOV_TOKEN" ]; then
            curl -s https://codecov.io/bash | bash -s -- -t $CODECOV_TOKEN -f $COVERAGE_FILE
          fi
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
          COVERAGE_FILE: ./coverage/php/clover.xml
        if: matrix.php == '7.3' && (env.RUNNING)
      - uses: 8398a7/action-slack@v2
        with:
          status: failure
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: failure()

  slack:
    name: Slack
    needs: [cover, phpunit]
    runs-on: ubuntu-latest
    steps:
      - uses: 8398a7/action-slack@v2
        with:
          status: success
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
