on: pull_request
name: Add label to PR
jobs:
  prLabeler:
    name: PR Labeler
    runs-on: ubuntu-latest
    steps:
      - name: PR Labeler
        if: github.event.action == 'opened'
        uses: technote-fork/pr-labeler-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  triage:
    name: Pull Request Labeler
    runs-on: ubuntu-latest
    steps:
      - name: Pull Request Labeler
        if: github.event.action == 'opened'
        uses: actions/labeler@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
