on: pull_request
name: Add label to PR
jobs:
  prLabeler:
    name: PR Labeler
    runs-on: ubuntu-latest
    steps:
      - name: PR opened filter
        uses: actions/bin/filter@master
        with:
          args: action opened
      - name: PR Labeler
        uses: TimonVS/pr-labeler@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  triage:
    name: Pull Request Labeler
    runs-on: ubuntu-latest
    steps:
      - name: Pull Request Labeler
        uses: actions/labeler@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
